name: CompassTeleport
author: Fycarman/Update by Assassiner354
version: 1.0
api: [3.0.0, 3.1.0, 3.2.0]
main: CompassTeleport\Main
depend: [FormAPI]
description: "Show a menu when the compass is clicked!"
